name: Deploy to Koyeb

on:
  workflow_dispatch:

env:
  IMAGE_NAME: stock-assistant
  APP_NAME: stock-assistant
  TF_WORKING_DIR: ./terraform
  TF_VERSION: "1.5.7"
  KOYEB_TOKEN: ${{ secrets.KOYEB_TOKEN }}
  TF_VAR_openai_api_key: ${{ secrets.OPENAI_API_KEY }}
  TF_VAR_duck_db_token: ${{ secrets.DUCK_DB_TOKEN }}
  TF_VAR_docker_image: ${{ secrets.DOCKERHUB_USERNAME }}/stock-assistant:latest
  TF_VAR_chainlit_auth_secret: ${{ secrets.CHAINLIT_AUTH_SECRET }}
  TF_VAR_auth_users: ${{ secrets.AUTH_USERS }}
  TF_VAR_dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
  TF_VAR_dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  deploy:
    name: Deploy to Koyeb via Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # had to use this as don't have terrafrom state
      # TODO: Add terraform cloud to manage state and remove this step
      - name: Delete Existing App
        run: |
          curl -fsSL https://raw.githubusercontent.com/koyeb/koyeb-cli/master/install.sh | sh
          export PATH=$PATH:$HOME/.koyeb/bin

          koyeb service delete ${{ env.APP_NAME }}-service --app ${{ env.APP_NAME }} || true
          koyeb app delete ${{ env.APP_NAME }} || true

          echo "Waiting 2 minutes for deletion to complete..."
          sleep 120
          echo "âœ… Deletion complete!"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format Check
        run: terraform fmt -recursive

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan       

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: | 
          terraform apply -auto-approve
          echo "Please wait 3 mins for the app to be deployed and healthy on Koyeb..."

      